### ISSUE TITLE
Multithreading Github Page is not up-to-date

### ISSUE THREAD

**Issue by HighnessAtharva** [learning-zone/java-interview-questions#14]
https://github.com/learning-zone/java-interview-questions/blob/master/multithreading-questions.md

This page was built but deployment failed so the Github Page for this is outdated based on the markdown file. Please deploy it to Github pages again.

**Comment by learning-zone** [comment]
@HighnessAtharva 

Github Page deployment is automatic, so just try refresh the page.

Thanks
