### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by aniketartani** [learning-zone/java-interview-questions#4]
I want to add the solution of Selection Sort.Please Assign me

**Comment by aniketartani** [comment]
I want to add the solution of Selection Sort.Please Assign me

**Comment by learning-zone** [comment]
Hey Thanks Aniket Artani, 

Please add your answers in [Java Programs](https://github.com/learning-zone/java-interview-questions/blob/master/java-programs.md) section.
